<?php
/**
 * SalesManago — XML product feed generator.
 *
 * URL: /_admin/sm_feed_xml.php?token=<SALESMANAGO_CRON_TOKEN>
 *
 * Transforms the existing comparador TSV feeds (already generated by
 * feedmachine, with all prices / translations / categories / URLs resolved)
 * into Google Merchant Center XML (RSS 2.0 + g: namespace), one per language.
 *
 *   /fm-feeds/comparador.txt          (ES)  →  /fm-feeds/sm-feed-es.xml
 *   /fm-feeds/comparador_ingles.txt   (EN)  →  /fm-feeds/sm-feed-en.xml
 *
 * SM reads each XML every 2h. We regenerate after the comparador TSVs refresh.
 *
 * Memory-safe: streams line by line, never loads the whole file.
 */

require_once 'includes/application_top.php';

@set_time_limit(290);
@ini_set('display_errors', '0');
header('Content-Type: text/plain; charset=utf-8');

// --- Auth ---
$token = $_GET['token'] ?? '';
$expected = defined('SALESMANAGO_CRON_TOKEN') ? (string) SALESMANAGO_CRON_TOKEN : '';
if ($expected === '' || !hash_equals($expected, (string) $token)) {
    http_response_code(403);
    echo "forbidden\n";
    exit;
}

$feedsDir = DIR_FS_CATALOG . 'fm-feeds/';

$jobs = [
    ['lang' => 'es', 'src' => $feedsDir . 'comparador.txt',         'dst' => $feedsDir . 'sm-feed-es.xml', 'title' => 'Francobordo ES'],
    ['lang' => 'en', 'src' => $feedsDir . 'comparador_ingles.txt',  'dst' => $feedsDir . 'sm-feed-en.xml', 'title' => 'Francobordo EN'],
];

/**
 * Make a string safe for XML 1.0:
 *  1. Drop invalid UTF-8 byte sequences (feedmachine truncates descriptions and
 *     can chop a multibyte char in half, leaving an orphan byte like 0xE2).
 *  2. Strip control characters illegal in XML 1.0 (even inside CDATA).
 * Note: no /u flag on the control-char regex — after step 1 the string is valid
 * UTF-8, and 0x00-0x1F never appear as UTF-8 continuation bytes, so byte-level
 * stripping is safe. (With /u, preg_replace returns null on invalid UTF-8.)
 */
function sm_xml_clean(string $s): string
{
    $s = @iconv('UTF-8', 'UTF-8//IGNORE', $s);
    if ($s === false) $s = '';
    $s = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $s);
    return $s ?? '';
}

/**
 * Strip tracking params (utm_*, etc.) from a product URL, keeping only the
 * params SM needs: `language` and (for variants) `attr`. Order: language, attr.
 * Input must be an already entity-decoded URL.
 */
function sm_clean_url(string $url): string
{
    $parts = parse_url($url);
    if ($parts === false || empty($parts['query'])) return $url;

    parse_str($parts['query'], $params);
    $ordered = [];
    if (isset($params['language'])) $ordered['language'] = $params['language'];
    if (isset($params['attr']))     $ordered['attr']     = $params['attr'];

    $base = ($parts['scheme'] ?? 'https') . '://' . ($parts['host'] ?? '') . ($parts['path'] ?? '');
    if (!empty($ordered)) {
        $base .= '?' . http_build_query($ordered);
    }
    return $base;
}

/** Map Google-feed availability strings → g:availability values. */
function sm_xml_availability(string $v): string
{
    $v = strtolower(trim($v));
    if ($v === '' )                    return 'in stock';
    if (str_contains($v, 'out'))       return 'out of stock';
    if (str_contains($v, 'preorder'))  return 'preorder';
    return 'in stock';
}

foreach ($jobs as $job) {
    $src = $job['src'];
    $dst = $job['dst'];

    if (!is_readable($src)) {
        echo "SKIP {$job['lang']}: source not readable ($src)\n";
        continue;
    }

    $tStart = microtime(true);
    $in  = fopen($src, 'r');
    $tmp = $dst . '.tmp';
    $out = fopen($tmp, 'w');

    // Header
    fwrite($out, '<?xml version="1.0" encoding="UTF-8"?>' . "\n");
    fwrite($out, '<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">' . "\n");
    fwrite($out, "<channel>\n");
    fwrite($out, '<title>' . htmlspecialchars($job['title'], ENT_XML1) . "</title>\n");
    fwrite($out, '<link>https://www.francobordo.com</link>' . "\n");
    fwrite($out, "<description>SalesManago product feed</description>\n");

    // Header row → column index map
    $headerLine = fgets($in);
    $cols = array_flip(array_map('trim', explode("\t", rtrim($headerLine, "\r\n"))));
    $col = fn($row, $name) => isset($cols[$name]) && isset($row[$cols[$name]]) ? $row[$cols[$name]] : '';

    $n = 0;
    while (($line = fgets($in)) !== false) {
        $row = explode("\t", rtrim($line, "\r\n"));
        if (count($row) < 3) continue;

        // Decode HTML entities from the TSV, then output as CDATA/escaped XML.
        $id    = trim($col($row, 'id'));
        if ($id === '') continue;

        $title = sm_xml_clean(html_entity_decode($col($row, 'title'), ENT_QUOTES, 'UTF-8'));
        $desc  = sm_xml_clean(html_entity_decode($col($row, 'description'), ENT_QUOTES, 'UTF-8'));
        $brand = sm_xml_clean(html_entity_decode($col($row, 'brand'), ENT_QUOTES, 'UTF-8'));
        $gcat  = sm_xml_clean(html_entity_decode($col($row, 'google_product_category'), ENT_QUOTES, 'UTF-8'));
        $ptype = sm_xml_clean(html_entity_decode(str_replace('-', ' > ', $col($row, 'product_type')), ENT_QUOTES, 'UTF-8'));
        // URLs already entity-encoded in TSV → decode, strip UTM (keep language/attr), then XML-escape
        $link  = sm_clean_url(sm_xml_clean(html_entity_decode($col($row, 'link'), ENT_QUOTES, 'UTF-8')));
        $img   = sm_xml_clean(html_entity_decode($col($row, 'image_link'), ENT_QUOTES, 'UTF-8'));
        $price = trim($col($row, 'price'));
        $mpn   = trim($col($row, 'mpn'));
        $gtin  = trim($col($row, 'gtin'));
        $cond  = trim($col($row, 'condition')) ?: 'new';
        $avail = sm_xml_availability($col($row, 'availability'));

        $item  = "<item>\n";
        $item .= '<g:id>' . htmlspecialchars($id, ENT_XML1) . "</g:id>\n";
        $item .= '<g:title><![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $title) . "]]></g:title>\n";
        if ($desc !== '')  $item .= '<g:description><![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $desc) . "]]></g:description>\n";
        $item .= '<g:link>' . htmlspecialchars($link, ENT_XML1) . "</g:link>\n";
        if ($img !== '')   $item .= '<g:image_link>' . htmlspecialchars($img, ENT_XML1) . "</g:image_link>\n";
        if ($price !== '') $item .= '<g:price>' . htmlspecialchars($price, ENT_XML1) . "</g:price>\n";
        if ($brand !== '') $item .= '<g:brand><![CDATA[' . $brand . "]]></g:brand>\n";
        if ($mpn !== '')   $item .= '<g:mpn>' . htmlspecialchars($mpn, ENT_XML1) . "</g:mpn>\n";
        if ($gtin !== '')  $item .= '<g:gtin>' . htmlspecialchars($gtin, ENT_XML1) . "</g:gtin>\n";
        $item .= '<g:condition>' . htmlspecialchars($cond, ENT_XML1) . "</g:condition>\n";
        $item .= '<g:availability>' . $avail . "</g:availability>\n";
        if ($gcat !== '')  $item .= '<g:google_product_category><![CDATA[' . $gcat . "]]></g:google_product_category>\n";
        if ($ptype !== '') $item .= '<g:product_type><![CDATA[' . $ptype . "]]></g:product_type>\n";
        $item .= "</item>\n";

        fwrite($out, $item);
        $n++;
    }

    fwrite($out, "</channel>\n</rss>\n");
    fclose($in);
    fclose($out);

    // Atomic move into place
    rename($tmp, $dst);
    @chmod($dst, 0644);

    $elapsed = round((microtime(true) - $tStart) * 1000);
    echo "OK {$job['lang']}: $n items → " . basename($dst) . " (" . round(filesize($dst) / 1048576, 1) . " MB, {$elapsed} ms)\n";
}

echo "done\n";
