<?php
/**
 * SalesManago — XML product feed generator.
 *
 * URL: /_admin/sm_feed_xml.php?token=<SALESMANAGO_CRON_TOKEN>
 *
 * Transforms the existing comparador TSV feeds (already generated by
 * feedmachine, with all prices / translations / categories / URLs resolved)
 * into Google Merchant Center XML (RSS 2.0 + g: namespace), one per language.
 *
 *   /fm-feeds/comparador.txt          (ES)  →  /fm-feeds/sm-feed-es.xml
 *   /fm-feeds/comparador_ingles.txt   (EN)  →  /fm-feeds/sm-feed-en.xml
 *
 * SM reads each XML every 2h. We regenerate after the comparador TSVs refresh.
 *
 * Memory-safe: streams line by line, never loads the whole file.
 */

require_once 'includes/application_top.php';

@set_time_limit(290);
@ini_set('display_errors', '0');
header('Content-Type: text/plain; charset=utf-8');

// --- Auth ---
$token = $_GET['token'] ?? '';
$expected = defined('SALESMANAGO_CRON_TOKEN') ? (string) SALESMANAGO_CRON_TOKEN : '';
if ($expected === '' || !hash_equals($expected, (string) $token)) {
    http_response_code(403);
    echo "forbidden\n";
    exit;
}

$feedsDir = DIR_FS_CATALOG . 'fm-feeds/';

$jobs = [
    ['lang' => 'es', 'src' => $feedsDir . 'comparador.txt',         'dst' => $feedsDir . 'sm-feed-es.xml', 'title' => 'Francobordo ES'],
    ['lang' => 'en', 'src' => $feedsDir . 'comparador_ingles.txt',  'dst' => $feedsDir . 'sm-feed-en.xml', 'title' => 'Francobordo EN'],
];

/**
 * Make a string safe for XML 1.0:
 *  1. Drop invalid UTF-8 byte sequences (feedmachine truncates descriptions and
 *     can chop a multibyte char in half, leaving an orphan byte like 0xE2).
 *  2. Strip control characters illegal in XML 1.0 (even inside CDATA).
 * Note: no /u flag on the control-char regex — after step 1 the string is valid
 * UTF-8, and 0x00-0x1F never appear as UTF-8 continuation bytes, so byte-level
 * stripping is safe. (With /u, preg_replace returns null on invalid UTF-8.)
 */
function sm_xml_clean(string $s): string
{
    $s = @iconv('UTF-8', 'UTF-8//IGNORE', $s);
    if ($s === false) $s = '';
    // C0 control chars (byte level — they never appear as UTF-8 continuation bytes)
    $s = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $s) ?? $s;
    // DEL + C1 control chars (U+007F–U+009F). These are valid UTF-8 (e.g. U+0090
    // = 0xC2 0x90) so iconv keeps them, but XML/SM import reject them. Strip at
    // codepoint level — safe here because the string is already valid UTF-8.
    $s = preg_replace('/[\x{007F}-\x{009F}]/u', '', $s) ?? $s;
    return $s;
}

/**
 * Clean a descriptive text field for SM import. SM rejects feeds whose text
 * fields contain shortcodes, incomplete HTML fragments, bullet symbols, etc.
 * Applied to title / description / brand / categories.
 *
 * Steps (order matters):
 *  1. sm_xml_clean   — valid UTF-8 + drop XML-illegal control chars.
 *  2. shortcodes     — remove [list_down ...], [/list_down], any [..].
 *  3. complete tags  — strip_tags removes well-formed <...> tags.
 *  4. broken tags    — remove leftover '<...'/'>' fragments (the feed truncates
 *                      descriptions to ~900 chars and can cut a tag like '<td' ).
 *  5. bullets/nbsp   — bullets (●•◦▪‣·) → '- '; nbsp → normal space.
 *  6. whitespace     — collapse runs of spaces/newlines into single spaces.
 */
function sm_text_clean(string $s): string
{
    $s = sm_xml_clean($s);
    // 2) shortcodes  [anything]  + truncated trailing '[list_down' with no ']'
    $s = preg_replace('/\[[^\]]*\]/u', ' ', $s) ?? $s;
    $s = preg_replace('/\[[^\]]*$/u', ' ', $s) ?? $s;   // dangling '[...' cut by truncation
    // bare shortcode-name remnants left by odd truncation (e.g. '/ list_down').
    // 'list_down' is the theme's only shortcode and never legit product text.
    $s = preg_replace('#/?\s*list_down\b#iu', ' ', $s) ?? $s;
    // 3) complete HTML tags
    $s = strip_tags($s);
    // 4) leftover broken tag fragments: '<' + rest with no closing '>' (truncated),
    //    or stray '<' / '>' that survived.
    $s = preg_replace('/<[^>]*$/u', ' ', $s) ?? $s;   // dangling '<td sty...' at the end
    $s = preg_replace('/<[^>]*>/u', ' ', $s) ?? $s;   // any other tag-like remnant
    $s = str_replace(['<', '>'], ' ', $s);            // truly stray angle brackets
    // 5) bullets and non-breaking spaces
    $s = preg_replace('/[\x{2022}\x{25CF}\x{25E6}\x{25AA}\x{2023}\x{00B7}\x{2219}\x{2043}]/u', '- ', $s) ?? $s;
    $s = str_replace("\xC2\xA0", ' ', $s);            // UTF-8 nbsp
    // 6) collapse whitespace
    $s = preg_replace('/\s+/u', ' ', $s) ?? $s;
    return trim($s);
}

/**
 * Reduce a product URL to the site's real canonical URL: strip the ENTIRE
 * query string (utm_*, language, attr, …). SM flags any "?param" as an
 * irregularity, and the canonical product page is clean anyway. Variants stay
 * uniquely identified by g:id ({products_id}-{products_attributes_id}); the
 * link just lands on the base product page.
 * Input must be an already entity-decoded URL.
 */
function sm_clean_url(string $url): string
{
    $parts = parse_url($url);
    if ($parts === false) return $url;
    return ($parts['scheme'] ?? 'https') . '://' . ($parts['host'] ?? '') . ($parts['path'] ?? '');
}

/** Map Google-feed availability strings → g:availability values. */
function sm_xml_availability(string $v): string
{
    $v = strtolower(trim($v));
    if ($v === '' )                    return 'in stock';
    if (str_contains($v, 'out'))       return 'out of stock';
    if (str_contains($v, 'preorder'))  return 'preorder';
    return 'in stock';
}

foreach ($jobs as $job) {
    $src = $job['src'];
    $dst = $job['dst'];

    if (!is_readable($src)) {
        echo "SKIP {$job['lang']}: source not readable ($src)\n";
        continue;
    }

    $tStart = microtime(true);
    $in  = fopen($src, 'r');
    $tmp = $dst . '.tmp';
    $out = fopen($tmp, 'w');

    // Header
    fwrite($out, '<?xml version="1.0" encoding="UTF-8"?>' . "\n");
    fwrite($out, '<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">' . "\n");
    fwrite($out, "<channel>\n");
    fwrite($out, '<title>' . htmlspecialchars($job['title'], ENT_XML1) . "</title>\n");
    fwrite($out, '<link>https://www.francobordo.com</link>' . "\n");
    fwrite($out, "<description>SalesManago product feed</description>\n");

    // Header row → column index map
    $headerLine = fgets($in);
    $cols = array_flip(array_map('trim', explode("\t", rtrim($headerLine, "\r\n"))));
    $col = fn($row, $name) => isset($cols[$name]) && isset($row[$cols[$name]]) ? $row[$cols[$name]] : '';

    $n = 0;
    $seen = [];   // dedup por g:id — el comparador repite filas por categoría
    $dups = 0;
    while (($line = fgets($in)) !== false) {
        $row = explode("\t", rtrim($line, "\r\n"));
        if (count($row) < 3) continue;

        // Decode HTML entities from the TSV, then output as CDATA/escaped XML.
        $id    = trim($col($row, 'id'));
        if ($id === '') continue;

        // Skip duplicate ids (same product in N categories → N feed rows).
        // Keep the first occurrence only.
        if (isset($seen[$id])) { $dups++; continue; }
        $seen[$id] = true;

        $title = sm_text_clean(html_entity_decode($col($row, 'title'), ENT_QUOTES, 'UTF-8'));
        $desc  = sm_text_clean(html_entity_decode($col($row, 'description'), ENT_QUOTES, 'UTF-8'));
        $brand = sm_text_clean(html_entity_decode($col($row, 'brand'), ENT_QUOTES, 'UTF-8'));
        $gcat  = sm_text_clean(html_entity_decode($col($row, 'google_product_category'), ENT_QUOTES, 'UTF-8'));
        // product_type: clean first, then build the ' > ' hierarchy separator
        // (doing it after cleaning so the '>' isn't stripped by sm_text_clean).
        $ptype = str_replace('-', ' > ', sm_text_clean(html_entity_decode($col($row, 'product_type'), ENT_QUOTES, 'UTF-8')));
        // URLs already entity-encoded in TSV → decode, strip UTM (keep language/attr), then XML-escape
        $link  = sm_clean_url(sm_xml_clean(html_entity_decode($col($row, 'link'), ENT_QUOTES, 'UTF-8')));
        $img   = sm_xml_clean(html_entity_decode($col($row, 'image_link'), ENT_QUOTES, 'UTF-8'));
        // id / price / mpn / condition: run through sm_xml_clean too — they can
        // also carry C1 control chars (e.g. an mpn like 'LISMART12100LX<U+0090>CHEMA').
        $id    = sm_xml_clean($id);
        $price = sm_xml_clean(trim($col($row, 'price')));
        // mpn: manufacturer part numbers are always ASCII (letters/digits/-./_ space).
        // Restrict to printable ASCII to drop mojibake + control chars in one go
        // (e.g. corrupt source 'LISMART12100LXâ‚¬<U+0090>MA' → 'LISMART12100LXMA').
        $mpn   = trim(preg_replace('/[^\x20-\x7E]/', '', sm_xml_clean(trim($col($row, 'mpn')))) ?? '');
        // Sanitize gtin: strip non-digits (fixes mojibake/spaces/letters) and
        // only keep it if a valid GTIN length remains (8/12/13/14). Otherwise
        // omit — an invalid gtin makes SM/Google reject the item as "invalid data".
        $gtin  = preg_replace('/\D/', '', (string) $col($row, 'gtin'));
        if (!in_array(strlen($gtin), [8, 12, 13, 14], true)) $gtin = '';
        $cond  = sm_xml_clean(trim($col($row, 'condition'))) ?: 'new';
        $avail = sm_xml_availability($col($row, 'availability'));

        $item  = "<item>\n";
        $item .= '<g:id>' . htmlspecialchars($id, ENT_XML1) . "</g:id>\n";
        $item .= '<g:title><![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $title) . "]]></g:title>\n";
        if ($desc !== '')  $item .= '<g:description><![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $desc) . "]]></g:description>\n";
        $item .= '<g:link>' . htmlspecialchars($link, ENT_XML1) . "</g:link>\n";
        if ($img !== '')   $item .= '<g:image_link>' . htmlspecialchars($img, ENT_XML1) . "</g:image_link>\n";
        if ($price !== '') $item .= '<g:price>' . htmlspecialchars($price, ENT_XML1) . "</g:price>\n";
        if ($brand !== '') $item .= '<g:brand><![CDATA[' . $brand . "]]></g:brand>\n";
        if ($mpn !== '')   $item .= '<g:mpn>' . htmlspecialchars($mpn, ENT_XML1) . "</g:mpn>\n";
        if ($gtin !== '')  $item .= '<g:gtin>' . htmlspecialchars($gtin, ENT_XML1) . "</g:gtin>\n";
        $item .= '<g:condition>' . htmlspecialchars($cond, ENT_XML1) . "</g:condition>\n";
        $item .= '<g:availability>' . $avail . "</g:availability>\n";
        if ($gcat !== '')  $item .= '<g:google_product_category><![CDATA[' . $gcat . "]]></g:google_product_category>\n";
        if ($ptype !== '') $item .= '<g:product_type><![CDATA[' . $ptype . "]]></g:product_type>\n";
        $item .= "</item>\n";

        fwrite($out, $item);
        $n++;
    }

    fwrite($out, "</channel>\n</rss>\n");
    fclose($in);
    fclose($out);

    // Atomic move into place
    rename($tmp, $dst);
    @chmod($dst, 0644);

    $elapsed = round((microtime(true) - $tStart) * 1000);
    echo "OK {$job['lang']}: $n items (dedup: $dups dupes omitidos) → " . basename($dst) . " (" . round(filesize($dst) / 1048576, 1) . " MB, {$elapsed} ms)\n";
}

echo "done\n";
